package cimgui

import (
	"github.com/jurgen-kluft/ccode/denv"
	cglfw "github.com/jurgen-kluft/cglfw/package"
	cunittest "github.com/jurgen-kluft/cunittest/package"
)

const (
	repo_path = "github.com\\jurgen-kluft"
	repo_name = "cimgui"
)

func GetPackage() *denv.Package {
	name := repo_name

	// dependencies
	cunittestpkg := cunittest.GetPackage()
	glfwpkg := cglfw.GetPackage()

	// main package
	mainpkg := denv.NewPackage(repo_path, repo_name)
	mainpkg.AddPackage(cunittestpkg)
	mainpkg.AddPackage(glfwpkg)

	// main library
	mainlib := denv.SetupCppLibProject(mainpkg, name)
	mainlib.AddDependencies(glfwpkg.GetMainLib())

	// a single library per backend
	imgui_impl_allegro5 := denv.SetupCppLibraryCustom(mainpkg, "backend_allegro5")
	imgui_impl_allegro5.AddInclude("source/backend_allegro5", ".h")
	imgui_impl_allegro5.AddSourceFiles("source/backend_allegro5", ".cpp")
	imgui_impl_allegro5.AddDependency(mainlib)
	imgui_impl_android := denv.SetupCppLibraryCustom(mainpkg, "backend_android")
	imgui_impl_android.AddInclude("source/backend_android", ".h")
	imgui_impl_android.AddSourceFiles("source/backend_android", ".cpp")
	imgui_impl_android.AddDependency(mainlib)
	imgui_impl_dx9 := denv.SetupCppLibraryCustom(mainpkg, "backend_dx9")
	imgui_impl_dx9.AddInclude("source/backend_dx9", ".h")
	imgui_impl_dx9.AddSourceFiles("source/backend_dx9", ".cpp")
	imgui_impl_dx9.AddDependency(mainlib)
	imgui_impl_dx9.SetBuildTargets(denv.BuildTargetWindowsX64)
	imgui_impl_dx10 := denv.SetupCppLibraryCustom(mainpkg, "backend_dx10")
	imgui_impl_dx10.AddInclude("source/backend_dx10", ".h")
	imgui_impl_dx10.AddSourceFiles("source/backend_dx10", ".cpp")
	imgui_impl_dx10.AddDependency(mainlib)
	imgui_impl_dx10.SetBuildTargets(denv.BuildTargetWindowsX64)
	imgui_impl_dx11 := denv.SetupCppLibraryCustom(mainpkg, "backend_dx11")
	imgui_impl_dx11.AddInclude("source/backend_dx11", ".h")
	imgui_impl_dx11.AddSourceFiles("source/backend_dx11", ".cpp")
	imgui_impl_dx11.AddDependency(mainlib)
	imgui_impl_dx11.SetBuildTargets(denv.BuildTargetWindowsX64)
	imgui_impl_dx12 := denv.SetupCppLibraryCustom(mainpkg, "backend_dx12")
	imgui_impl_dx12.AddInclude("source/backend_dx12", ".h")
	imgui_impl_dx12.AddSourceFiles("source/backend_dx12", ".cpp")
	imgui_impl_dx12.AddDependency(mainlib)
	imgui_impl_dx12.SetBuildTargets(denv.BuildTargetWindowsX64)
	imgui_impl_glfw := denv.SetupCppLibraryCustom(mainpkg, "backend_glfw")
	imgui_impl_glfw.AddInclude("source/backend_glfw", ".h")
	imgui_impl_glfw.AddSourceFiles("source/backend_glfw", ".cpp")
	imgui_impl_glfw.AddDependency(mainlib)
	imgui_impl_glut := denv.SetupCppLibraryCustom(mainpkg, "backend_glut")
	imgui_impl_glut.AddInclude("source/backend_glut", ".h")
	imgui_impl_glut.AddSourceFiles("source/backend_glut", ".cpp")
	imgui_impl_glut.AddDependency(mainlib)
	imgui_impl_metal := denv.SetupCppLibraryCustom(mainpkg, "backend_metal")
	imgui_impl_metal.AddInclude("source/backend_metal", ".h")
	imgui_impl_metal.AddSourceFiles("source/backend_metal", ".cpp", ".mm")
	imgui_impl_metal.AddDependency(mainlib)
	imgui_impl_metal.SetBuildTargets(denv.BuildTargetMacUniversal)
	imgui_impl_opengl2 := denv.SetupCppLibraryCustom(mainpkg, "backend_opengl2")
	imgui_impl_opengl2.AddInclude("source/backend_opengl2", ".h")
	imgui_impl_opengl2.AddSourceFiles("source/backend_opengl2", ".cpp")
	imgui_impl_opengl2.AddDependency(mainlib)
	imgui_impl_opengl3 := denv.SetupCppLibraryCustom(mainpkg, "backend_opengl3")
	imgui_impl_opengl3.AddInclude("source/backend_opengl3", ".h")
	imgui_impl_opengl3.AddSourceFiles("source/backend_opengl3", ".cpp")
	imgui_impl_opengl3.AddDependency(mainlib)
	imgui_impl_osx := denv.SetupCppLibraryCustom(mainpkg, "backend_osx")
	imgui_impl_osx.AddInclude("source/backend_osx", ".h")
	imgui_impl_osx.AddSourceFiles("source/backend_osx", ".cpp", ".mm")
	imgui_impl_osx.AddDependency(mainlib)
	imgui_impl_osx.SetBuildTargets(denv.BuildTargetMacUniversal)
	imgui_impl_sdl2 := denv.SetupCppLibraryCustom(mainpkg, "backend_sdl2")
	imgui_impl_sdl2.AddInclude("source/backend_sdl2", ".h")
	imgui_impl_sdl2.AddSourceFiles("source/backend_sdl2", ".cpp")
	imgui_impl_sdl2.AddDependency(mainlib)
	imgui_impl_sdl3 := denv.SetupCppLibraryCustom(mainpkg, "backend_sdl3")
	imgui_impl_sdl3.AddInclude("source/backend_sdl3", ".h")
	imgui_impl_sdl3.AddSourceFiles("source/backend_sdl3", ".cpp")
	imgui_impl_sdl3.AddDependency(mainlib)
	imgui_impl_sdlgpu3 := denv.SetupCppLibraryCustom(mainpkg, "backend_sdlgpu3")
	imgui_impl_sdlgpu3.AddInclude("source/backend_sdlgpu3", ".h")
	imgui_impl_sdlgpu3.AddSourceFiles("source/backend_sdlgpu3", ".cpp")
	imgui_impl_sdlgpu3.AddDependency(mainlib)
	imgui_impl_sdlrenderer2 := denv.SetupCppLibraryCustom(mainpkg, "backend_sdlrenderer2")
	imgui_impl_sdlrenderer2.AddInclude("source/backend_sdlrenderer2", ".h")
	imgui_impl_sdlrenderer2.AddSourceFiles("source/backend_sdlrenderer2", ".cpp")
	imgui_impl_sdlrenderer2.AddDependency(mainlib)
	imgui_impl_sdlrenderer3 := denv.SetupCppLibraryCustom(mainpkg, "backend_sdlrenderer3")
	imgui_impl_sdlrenderer3.AddInclude("source/backend_sdlrenderer3", ".h")
	imgui_impl_sdlrenderer3.AddSourceFiles("source/backend_sdlrenderer3", ".cpp")
	imgui_impl_sdlrenderer3.AddDependency(mainlib)
	imgui_impl_vulkan := denv.SetupCppLibraryCustom(mainpkg, "backend_vulkan")
	imgui_impl_vulkan.AddInclude("source/backend_vulkan", ".h")
	imgui_impl_vulkan.AddSourceFiles("source/backend_vulkan", ".cpp")
	imgui_impl_vulkan.AddDependency(mainlib)
	imgui_impl_vulkan.SetBuildTargets(denv.BuildTargetLinuxUniversal)
	imgui_impl_wgpu := denv.SetupCppLibraryCustom(mainpkg, "backend_wgpu")
	imgui_impl_wgpu.AddInclude("source/backend_wgpu", ".h")
	imgui_impl_wgpu.AddSourceFiles("source/backend_wgpu", ".cpp")
	imgui_impl_wgpu.AddDependency(mainlib)
	imgui_impl_win32 := denv.SetupCppLibraryCustom(mainpkg, "backend_win32")
	imgui_impl_win32.AddInclude("source/backend_win32", ".h")
	imgui_impl_win32.AddSourceFiles("source/backend_win32", ".cpp")
	imgui_impl_win32.AddDependency(mainlib)
	imgui_impl_win32.SetBuildTargets(denv.BuildTargetWindowsX64)

	mainpkg.AddMainLib(mainlib)
	mainpkg.AddLibrary(imgui_impl_allegro5)
	mainpkg.AddLibrary(imgui_impl_android)
	mainpkg.AddLibrary(imgui_impl_dx9)
	mainpkg.AddLibrary(imgui_impl_dx10)
	mainpkg.AddLibrary(imgui_impl_dx11)
	mainpkg.AddLibrary(imgui_impl_dx12)
	mainpkg.AddLibrary(imgui_impl_glfw)
	mainpkg.AddLibrary(imgui_impl_glut)
	mainpkg.AddLibrary(imgui_impl_metal)
	mainpkg.AddLibrary(imgui_impl_opengl2)
	mainpkg.AddLibrary(imgui_impl_opengl3)
	mainpkg.AddLibrary(imgui_impl_osx)
	mainpkg.AddLibrary(imgui_impl_sdl2)
	mainpkg.AddLibrary(imgui_impl_sdl3)
	mainpkg.AddLibrary(imgui_impl_sdlgpu3)
	mainpkg.AddLibrary(imgui_impl_sdlrenderer2)
	mainpkg.AddLibrary(imgui_impl_sdlrenderer3)
	mainpkg.AddLibrary(imgui_impl_vulkan)
	mainpkg.AddLibrary(imgui_impl_wgpu)
	mainpkg.AddLibrary(imgui_impl_win32)
	return mainpkg
}
